### ISSUE TITLE
Browsersync redirect on password protected sites with custom domains

### ISSUE THREAD

**Issue by t-kelly** [Shopify/slate#234]
<a href="https://github.com/NathanPJF"><img src="https://avatars2.githubusercontent.com/u/6284114?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [NathanPJF](https://github.com/NathanPJF)**
_Monday Jul 10, 2017 at 02:23 GMT_
_Originally opened as https://github.com/Shopify/slate-tools/issues/74_

----

## Problem

Password protected storefronts with custom domains are unable to rely on the sync commands run by `slate watch`.  

This has been mentioned in a couple issues in the framework repo.
* https://github.com/Shopify/slate/issues/182 Question: why when I run `slate watch` i get redirected to "store.com/password" instead of local dev environment? 
* https://github.com/Shopify/slate/issues/145 Preview Password Protected Site Locally

Storefronts without password protection are unaffected.  More on that below in the "More information" section.

### Scope

There are two ways the redirection issue is causing problems:
1. Storefronts where the primary domain is custom, but traffic **is not** redirected to the primary domain.
2. Storefronts with custom domains and traffic **is** being redirected.

## Replication steps

* Have a site with a custom domain and SSL enabled.  For SSL activation, see more at this doc:  https://help.shopify.com/manual/domains/ssl
* In the domains admin, `/admin/settings/domains`, set your primary domain to be the custom domain.

### Custom domain, no forced redirect

Video of issue: http://take.ms/6LO6X
* The store's primary domain is `slate-demo.com`; redirect is not enabled.
* Run `slate watch -e development`.  Browsersync opens up `locahlhost:3000/password` for the **correct** development theme.
* The password form has the **incorrect** `action` parameter.  It should be `localhost:3000/password`, not `slate-demo.com/password`.
* Submitting the password then redirects the user to the public site, instead of staying at `localhost`.

The issue here is the `action` parameter.  With the correct `action` attribute, the site works as expected.  Video of me changing the `action` manually in the inspector: https://screenshot.click/screencast_2017-07-09_21-52-23.mp4

### Custom domain, forced redirect

Video of issue: http://take.ms/Lcbmy5
* The store's primary domain is `slate-demo.com`; redirect **is enabled**.
* Note: Be sure to clear your cookies so your previous logged in session doesn't influence your testing.  More on that below in "testing quirk".
* Run `slate watch -e development`.  Browsersync attempts to open `locahlhost:3000/password`, but the forced redirect sends you to the public site.

### Force redirects URL parameter

The subject of force redirection was already considered in the development of Slate tools.  You can see a comment in the code here with the use of `_fd`.  https://github.com/Shopify/slate-tools/blob/master/src/tasks/deploy-sync.js#L31  Worth following up on this lead.

When the password is **not enabled**, there is no issue with forcing redirection and `localhost`, as seen in this video: http://take.ms/ywNBn
* Redirection is enabled; run `slate watch`.
* The URL that is loaded is `localhost:3000?_fd=0`

### Testing quirk
There is a quirk in testing where you can have a password enabled site and a forced redirect, but still be able to have Browsersync stay connected with `localhost:3000`.  Video here: http://take.ms/DNlTW
* Turn off redirection and then run `slate watch`.
* Manually correct the `action` parameter on the password form and log in.
* You can now turn redirection back on.
* And the current `watch` task and start a new one.  You'll still be logged in from your session before and stay on `localhost:3000`.

^ Definitely not a solution - but something to be aware of when testing.

**Comment by t-kelly** [comment]
<a href="https://github.com/wadehammes"><img src="https://avatars1.githubusercontent.com/u/222170?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wadehammes](https://github.com/wadehammes)**
_Monday Jul 31, 2017 at 16:00 GMT_

----

I am having an issue with this too. Our site is PW enabled, and cannot spin up a local instance of the theme in order to do dev, as the `localhost` url redirects to `our-store-name.myshopify.com/password`, very frustrating.

**Comment by slyedoc** [comment]
Workaround:  If you go to preview the theme from admin, you will get a URL with a 'key' param, add that to your localhost URL it gets you in pass the password page.

Example: 
 https://localhost:3000?key=2c2032e7c8183a0d1d32c85263ddcfdfcdae8caa5d3b0dc078f94dbd0818ea6a

**Comment by t-kelly** [comment]
Both scenarios described by Nathan are bugs with Shopify core, not Slate. Will leave this open until we get those bugs fixed!

**Comment by t-kelly** [comment]
Looks like the two issues raised in core will take a little longer to fix. Going to move this issue to the next release, `v0.13.0`

**Comment by t-kelly** [comment]
Actually on second thought, all of the changes needed to fix this are in core so this doesn't need to be part of the next release. Will close this issue when the fixes have shipped.

**Comment by t-kelly** [comment]
The first issue described in the issue had been fixed and deployed! All form URLs are now relative, e.g. `/password` instead of `https://mydomain.com/password`. This will ensure you stay on localhost with Slate.

**Comment by t-kelly** [comment]
These are both now fixed in core! 🎉

**Comment by jeffmon** [comment]
I'm still having the same issue and won't let me preview the theme. No passwords work either.

**Comment by t-kelly** [comment]
@jeffmon make sure your `slate-tools` dependency in your theme `package.json` is updated to `0.12.1`.

**Comment by davicho** [comment]
Same as @jeffmon , I can only access disabling password (I would like to have it on). `slate-tools` = `0.13.0`
